//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.1.
// 
#pragma warning disable 1591

namespace TennisWMC.wsTennis {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.ComponentModel;
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="ServiceSoap", Namespace="http://amarkota.com/webservices/tennis")]
    public partial class Service : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback GetTennisScoresForWMCOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public Service() {
            this.Url = global::TennisWMC.Properties.Settings.Default.TennisWMC_wsTennis_Service;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event GetTennisScoresForWMCCompletedEventHandler GetTennisScoresForWMCCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://amarkota.com/webservices/tennis/GetTennisScoresForWMC", RequestNamespace="http://amarkota.com/webservices/tennis", ResponseNamespace="http://amarkota.com/webservices/tennis", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public TennisScoresCollection GetTennisScoresForWMC(ScoreTypes scoreType) {
            object[] results = this.Invoke("GetTennisScoresForWMC", new object[] {
                        scoreType});
            return ((TennisScoresCollection)(results[0]));
        }
        
        /// <remarks/>
        public void GetTennisScoresForWMCAsync(ScoreTypes scoreType) {
            this.GetTennisScoresForWMCAsync(scoreType, null);
        }
        
        /// <remarks/>
        public void GetTennisScoresForWMCAsync(ScoreTypes scoreType, object userState) {
            if ((this.GetTennisScoresForWMCOperationCompleted == null)) {
                this.GetTennisScoresForWMCOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetTennisScoresForWMCOperationCompleted);
            }
            this.InvokeAsync("GetTennisScoresForWMC", new object[] {
                        scoreType}, this.GetTennisScoresForWMCOperationCompleted, userState);
        }
        
        private void OnGetTennisScoresForWMCOperationCompleted(object arg) {
            if ((this.GetTennisScoresForWMCCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetTennisScoresForWMCCompleted(this, new GetTennisScoresForWMCCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://amarkota.com/webservices/tennis")]
    public enum ScoreTypes {
        
        /// <remarks/>
        ALL_MATCHES,
        
        /// <remarks/>
        TIMELINE,
        
        /// <remarks/>
        NOT_STARTED,
        
        /// <remarks/>
        FINISHED,
        
        /// <remarks/>
        IN_PLAY,
        
        /// <remarks/>
        SCORESLINE,
        
        /// <remarks/>
        YESTERDAY,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://amarkota.com/webservices/tennis")]
    public partial class TennisScoresCollection {
        
        private Match[] singlesField;
        
        private Match[] doublesField;
        
        /// <remarks/>
        public Match[] Singles {
            get {
                return this.singlesField;
            }
            set {
                this.singlesField = value;
            }
        }
        
        /// <remarks/>
        public Match[] Doubles {
            get {
                return this.doublesField;
            }
            set {
                this.doublesField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://amarkota.com/webservices/tennis")]
    public partial class Match {
        
        private int matchIndexField;
        
        private string courtField;
        
        private bool inProgressField;
        
        private MatchProgress statusField;
        
        private Player player1Field;
        
        private Player player2Field;
        
        private string durationField;
        
        private System.DateTime datePlayedField;
        
        private string tournamentField;
        
        private string surfaceTypeField;
        
        private MatchTypes matchTypeField;
        
        /// <remarks/>
        public int MatchIndex {
            get {
                return this.matchIndexField;
            }
            set {
                this.matchIndexField = value;
            }
        }
        
        /// <remarks/>
        public string Court {
            get {
                return this.courtField;
            }
            set {
                this.courtField = value;
            }
        }
        
        /// <remarks/>
        public bool InProgress {
            get {
                return this.inProgressField;
            }
            set {
                this.inProgressField = value;
            }
        }
        
        /// <remarks/>
        public MatchProgress Status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
            }
        }
        
        /// <remarks/>
        public Player Player1 {
            get {
                return this.player1Field;
            }
            set {
                this.player1Field = value;
            }
        }
        
        /// <remarks/>
        public Player Player2 {
            get {
                return this.player2Field;
            }
            set {
                this.player2Field = value;
            }
        }
        
        /// <remarks/>
        public string Duration {
            get {
                return this.durationField;
            }
            set {
                this.durationField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime DatePlayed {
            get {
                return this.datePlayedField;
            }
            set {
                this.datePlayedField = value;
            }
        }
        
        /// <remarks/>
        public string Tournament {
            get {
                return this.tournamentField;
            }
            set {
                this.tournamentField = value;
            }
        }
        
        /// <remarks/>
        public string SurfaceType {
            get {
                return this.surfaceTypeField;
            }
            set {
                this.surfaceTypeField = value;
            }
        }
        
        /// <remarks/>
        public MatchTypes MatchType {
            get {
                return this.matchTypeField;
            }
            set {
                this.matchTypeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://amarkota.com/webservices/tennis")]
    public enum MatchProgress {
        
        /// <remarks/>
        NOT_STARTED,
        
        /// <remarks/>
        IN_PLAY,
        
        /// <remarks/>
        FINISHED,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://amarkota.com/webservices/tennis")]
    public partial class Player {
        
        private GamePoint[] gamesWonField;
        
        private string nameField;
        
        private bool isWinnerField;
        
        /// <remarks/>
        public GamePoint[] GamesWon {
            get {
                return this.gamesWonField;
            }
            set {
                this.gamesWonField = value;
            }
        }
        
        /// <remarks/>
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        public bool IsWinner {
            get {
                return this.isWinnerField;
            }
            set {
                this.isWinnerField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://amarkota.com/webservices/tennis")]
    public partial class GamePoint {
        
        private int scoreField;
        
        private int setField;
        
        private bool isWinnerField;
        
        /// <remarks/>
        public int Score {
            get {
                return this.scoreField;
            }
            set {
                this.scoreField = value;
            }
        }
        
        /// <remarks/>
        public int Set {
            get {
                return this.setField;
            }
            set {
                this.setField = value;
            }
        }
        
        /// <remarks/>
        public bool IsWinner {
            get {
                return this.isWinnerField;
            }
            set {
                this.isWinnerField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://amarkota.com/webservices/tennis")]
    public enum MatchTypes {
        
        /// <remarks/>
        SINGLES,
        
        /// <remarks/>
        DOUBLES,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void GetTennisScoresForWMCCompletedEventHandler(object sender, GetTennisScoresForWMCCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetTennisScoresForWMCCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetTennisScoresForWMCCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public TennisScoresCollection Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((TennisScoresCollection)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591